name: BDML
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - libaio
  - gxx_linux-64=11.3
  - openjdk=8
  - pkg-config
  - cmake
  - pip:
    - pandas
    - matplotlib
    - seaborn
    - jupyter
    - notebook
    # - --extra-index-url https://download.pytorch.org/whl/cu118
    - -r ./requirements.txt
